version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash -c "rm -f /tmp/server.pid && bundle exec rails server -b 0.0.0.0 -P /tmp/server.pid"
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      SELENIUM_REMOTE_URL: http://webdriver_chrome:4444/wd/hub
      PG_PASSWORD: password
    tty: true
    stdin_open: true
    depends_on:
      - webpacker
      - postgres
      - webdriver_chrome
  webpacker:
    build: .
    command: bash -c "rm -rf /app/public/packs; /app/bin/webpack-dev-server"
    volumes:
      - .:/app
    ports:
      - 3035:3035
  postgres:
    image: postgres:10.5-alpine
    ports:
      - 5432:5432
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  webdriver_chrome:
      image: selenium/standalone-chrome
